name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      checks: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      # Bevy dependencies
      - run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev

      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test